name: goppa
on: pull_request
jobs:
  goppa:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install goppa
        run: go install github.com/masibw/goppa@latest
      - name: Load previous test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.base_ref }}
      - name: Load current test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.head_ref }}
      - name: Run goppa
        run: goppa --previous ./test-${{ github.base_ref }}.log --current ./test-${{ github.head_ref }}.log