name: test
on: push
jobs:
  test:
    name: Test local sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: go mod download -x
<<<<<<< Updated upstream
      - name: Test
        run: go test -v ./...  > ./test-${{ github.ref_name }}.log
      - name: Save test results
||||||| constructed merge base
      - name: Test
        run: go test -v ./...  > ./test-${{ github.head_ref }}.log
      - name: Save test results
=======
      - name: Test(on Pull Request)
        if: ${{ github.event_name }} == "pull_request"
        run: go test -v ./...  > ./test-${{ github.head_ref }}.log
      - name: Test(on Push)
        if: ${{ github.event_name }} == "push"
        run: go test -v ./...  > ./test-${{ github.ref_name }}.log
      - name: Save test results(on Pull Request)
        if: ${{ github.event_name }} == "pull_request"
>>>>>>> Stashed changes
        uses: actions/upload-artifact@v2
        with:
<<<<<<< Updated upstream
          name: test-${{ github.ref_name }}
          path: ./test-${{ github.ref_name }}.log
||||||| constructed merge base
          name: test-${{ github.head_ref }}
          path: ./test-${{ github.head_ref }}.log

  goppa:
    if: ${{ github.event_name }} == "pull_request"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install goppa
        run: go install github.com/masibw/goppa@latest
      - name: Load previous test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.base_ref }}
      - name: Load current test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.head_ref }}
      - name: Run goppa
        run: goppa --previous ./test-${{ github.base_ref }}.log --current ./test-${{ github.head_ref }}.log
=======
          name: test-${{ github.head_ref }}
          path: ./test-${{ github.head_ref }}.log
      - name: Save test results(on Push)
        if: ${{ github.event_name }} == "push"
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ github.ref_name }}
          path: ./test-${{ github.ref_name }}.log

  goppa:
    if: ${{ github.event_name }} == "pull_request"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install goppa
        run: go install github.com/masibw/goppa@latest
      - name: Load previous test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.base_ref }}
      - name: Load current test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.head_ref }}
      - name: Run goppa
        run: goppa --previous ./test-${{ github.base_ref }}.log --current ./test-${{ github.head_ref }}.log
>>>>>>> Stashed changes
