name: test
on: pull_request
jobs:
  test:
    name: Test local sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: go mod download -x
      - name: Test
        run: go test -v ./...  > ./test-${{ github.head_ref }}.log
      - name: Save test results
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ github.head_ref }}
          path: ./test-${{ github.head_ref }}.log

  goppa:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install goppa
        run: go install github.com/masibw/goppa@latest
      - name: Load previous test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.base_ref }}
      - name: Load current test result
        uses: actions/download-artifact@v2
        with:
          name: test-${{ github.head_ref }}]
      - name: Run goppa
        if: always()
        run: goppa --previous ./test-${{ github.base_ref }}.log --current ./test-${{ github.head_ref }}.log


